// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaKltHKywzl8c1Na_PYQHL2t-A-ibpMwg',
    appId: '1:778815392352:web:260ba24812aa3ca48e5105',
    messagingSenderId: '778815392352',
    projectId: 'carreno-post2-u8',
    authDomain: 'carreno-post2-u8.firebaseapp.com',
    storageBucket: 'carreno-post2-u8.firebasestorage.app',
    measurementId: 'G-Q5GK9XK28J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBibHxnkQ5Fddm2mRnpEGMfb71FgFrfG94',
    appId: '1:778815392352:android:694aa42d65f9936e8e5105',
    messagingSenderId: '778815392352',
    projectId: 'carreno-post2-u8',
    storageBucket: 'carreno-post2-u8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGuy7LSmZBgN6R04RLoECkgxGC4aTXfWg',
    appId: '1:778815392352:ios:e2b4c81288186c068e5105',
    messagingSenderId: '778815392352',
    projectId: 'carreno-post2-u8',
    storageBucket: 'carreno-post2-u8.firebasestorage.app',
    iosBundleId: 'com.udes.carrenoPost2U8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGuy7LSmZBgN6R04RLoECkgxGC4aTXfWg',
    appId: '1:778815392352:ios:e2b4c81288186c068e5105',
    messagingSenderId: '778815392352',
    projectId: 'carreno-post2-u8',
    storageBucket: 'carreno-post2-u8.firebasestorage.app',
    iosBundleId: 'com.udes.carrenoPost2U8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaKltHKywzl8c1Na_PYQHL2t-A-ibpMwg',
    appId: '1:778815392352:web:e75d578147ae6a3f8e5105',
    messagingSenderId: '778815392352',
    projectId: 'carreno-post2-u8',
    authDomain: 'carreno-post2-u8.firebaseapp.com',
    storageBucket: 'carreno-post2-u8.firebasestorage.app',
    measurementId: 'G-0P29YELG40',
  );
}
